<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'App\Http\Controllers\IndexController@home');
Route::get('home', 'App\Http\Controllers\IndexController@home');
Route::get('index', 'App\Http\Controllers\IndexController@home');
Route::get('about','App\Http\Controllers\IndexController@about');
Route::get('services','App\Http\Controllers\IndexController@services');
Route::get('terms','App\Http\Controllers\IndexController@terms');
Route::get('setcookie', 'App\Http\Controllers\CookieController@setCookie');
Route::get('login', 'App\Http\Controllers\LoginController@check_login');
Route::post('login', 'App\Http\Controllers\LoginController@do_login');
Route::get('signup', 'App\Http\Controllers\LoginController@signup');
Route::post('signup', 'App\Http\Controllers\LoginController@do_signup');
Route::get('signup/check/{type}', 'App\Http\Controllers\LoginController@checkCredentials');
Route::get('forgotten_password','App\Http\Controllers\LoginController@forgotten_password');
Route::post('sendMail','App\Http\Controllers\LoginController@sendMail');
Route::post('search','App\Http\Controllers\MainController@show');
Route::get('search','App\Http\Controllers\MainController@search');
Route::get('result','App\Http\Controllers\MainController@result');
Route::post('review','App\Http\Controllers\MainController@review');
Route::get('review','App\Http\Controllers\IndexController@home');
Route::post("saveReview","App\Http\Controllers\MainController@saveReview");
Route::post("getLike","App\Http\Controllers\MainController@getLike");
Route::post("getReview","App\Http\Controllers\MainController@getReview");
Route::post("getReviewLikes","App\Http\Controllers\MainController@getReviewLikes");
Route::get("getRandomReviews","App\Http\Controllers\MainController@getRandomReviews");
Route::post("getNumLikes","App\Http\Controllers\MainController@getNumLikes");
Route::post("getNumReviews","App\Http\Controllers\MainController@getNumReviews");
Route::post("saveLikes","App\Http\Controllers\MainController@saveLikes");
Route::post("deleteLikes","App\Http\Controllers\MainController@deleteLikes");
Route::post("fetchMyReviewLikes","App\Http\Controllers\MainController@getMyReviewLikes");
Route::post("addReviewLike","App\Http\Controllers\MainController@addReviewLike");
Route::post("deleteReviewLike","App\Http\Controllers\MainController@deleteReviewLike");
Route::get('profile','App\Http\Controllers\MainController@profile');
Route::get('fetchMyReviews','App\Http\Controllers\MainController@getMyReviews');
Route::get('fetchMyLikedReviews','App\Http\Controllers\MainController@getMyLikedReviews');
Route::get("fetchUserAvatar",'App\Http\Controllers\MainController@getUserAvatar');
Route::post("deleteReview","App\Http\Controllers\MainController@deleteReview");
Route::post("changeSettings","App\Http\Controllers\MainController@changeSettings");
Route::get("fetchMyLikes",'App\Http\Controllers\MainController@countUserLikes');
Route::get("fetchReviewCount",'App\Http\Controllers\MainController@countUserReviews');
Route::get('logout', 'App\Http\Controllers\CookieController@deleteCookie');